services:
  web:
    image: nginx:latest 
    ports:
      - "8008:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app 
  php:
    image: php:fpm 
    volumes: 
      - ./app:/app
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql 
    ports:
      - 3306:3306
volumes:
  mysqldata: {}
